version: '3.8'

services:
  mariadb:
    build: 
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    image: mariadb:v1
    container_name: mariadb
    init: true
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    restart: always
    networks:
      - inception

  nextcloud:
    build:
      context: .
      dockerfile: requirements/nextcloud/Dockerfile
    image: nextcloud:v1
    container_name: nextcloud
    init: true
    volumes:
      - nextcloud:/var/www/html
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
      - /etc/letsencrypt/live:/etc/letsencrypt/live
    environment:
      REDIS_HOST: redis
      REDIS_HOST_PORT: 6379
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      NEXTCLOUD_ADMIN_USER: ${ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASS}
      DOMAIN_NAME: ${DOMAIN_NAME} 
    ports:
      - 8443:8443
    restart: always
    networks:
      - inception

  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    init: true
    depends_on:
      - mariadb
    volumes:
      - traccar:/opt/traccar/logs
      - traccar:/opt/traccar/data
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - 8082:8082
      - 5000-5150:5000-5150/tcp
      - 5000-5150:5000-5150/udp
    restart: always
    networks:
      - inception

  nginx:
    build: 
      context: .
      dockerfile: requirements/nginx/Dockerfile
    image: nginx:v1
    container_name: nginx
    init: true
    depends_on:
      - nextcloud
      - traccar
    volumes:
      - nextcloud:/var/www/html
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
      - /etc/letsencrypt/live:/etc/letsencrypt/live
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - inception

  redis:
    image: redis:alpine
    networks:
      - inception
    volumes:
      - redis:/data

volumes:
  nextcloud:
    driver: local
    driver_opts:
      type: none
      device: /var/data/nextcloud
      o: bind
  traccar:
    driver: local
    driver_opts:
      type: none
      device: /var/data/traccar
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: /var/data/db
      o: bind
  redis:
    driver: local
    driver_opts:
      type: none
      device: /var/data/redis
      o: bind

networks:
  inception:
    driver: bridge