linux:
  hosts:
    "{{ lookup('env', 'HOST_IP') }}":
        domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"
        domain_name2: "{{ lookup('env', 'DOMAIN_NAME2') }}"
        admin_email: "{{ lookup('env', 'ADMIN_EMAIL') }}"
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_PRIVATE_KEY_FILE') }}"